# Generated by Django 6.0.1 on 2026-02-20 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options_remove_project_live_demo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='full_description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='live_demo_link',
        ),
    ]
